package com.synergy.keimed_ordergenie.database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "CHEMIST_ORDER".
 */
@Entity
public class ChemistOrder {

    @Id(autoincrement = true)
    private Long id;
    private String OrderNo;
    private String ItemSrNo;
    private String Item_Name;
    private String MRP;
    private String Packsize;
    private String Qty;

    @Generated(hash = 1262039340)
    public ChemistOrder() {
    }

    public ChemistOrder(Long id) {
        this.id = id;
    }

    @Generated(hash = 668439647)
    public ChemistOrder(Long id, String OrderNo, String ItemSrNo, String Item_Name, String MRP, String Packsize, String Qty) {
        this.id = id;
        this.OrderNo = OrderNo;
        this.ItemSrNo = ItemSrNo;
        this.Item_Name = Item_Name;
        this.MRP = MRP;
        this.Packsize = Packsize;
        this.Qty = Qty;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getOrderNo() {
        return OrderNo;
    }

    public void setOrderNo(String OrderNo) {
        this.OrderNo = OrderNo;
    }

    public String getItemSrNo() {
        return ItemSrNo;
    }

    public void setItemSrNo(String ItemSrNo) {
        this.ItemSrNo = ItemSrNo;
    }

    public String getItem_Name() {
        return Item_Name;
    }

    public void setItem_Name(String Item_Name) {
        this.Item_Name = Item_Name;
    }

    public String getMRP() {
        return MRP;
    }

    public void setMRP(String MRP) {
        this.MRP = MRP;
    }

    public String getPacksize() {
        return Packsize;
    }

    public void setPacksize(String Packsize) {
        this.Packsize = Packsize;
    }

    public String getQty() {
        return Qty;
    }

    public void setQty(String Qty) {
        this.Qty = Qty;
    }

}
