package com.synergy.keimed_ordergenie.database;

import android.databinding.BaseObservable;
import android.databinding.Bindable;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "CHEMIST_CART".
 */
@Entity
public class ChemistCart extends BaseObservable {

    @Id(autoincrement = true)
    private Long id;
    private String DOC_ID;
    private String Stockist_Client_id;
    private String Items;
    private String Itemname;
    private String Amount;
    private String Remarks;
    private Boolean Salesman;
    private Boolean order_sync;
    private String Product_ID;
    private String Qty;
    private String UOM;
    private String Rate;
    private String Price;
    private String MRP;
    private String PACK;
    private String Createdon;
    private String Scheme;
    private String Sub_stkID;
    private String minQ;
    private String maxQ;



    private  String PercentScheme;
    private String HalfScheme;


    @Generated(hash = 1433490064)
    public ChemistCart() {
    }

    public ChemistCart(Long id) {
        this.id = id;
    }



    @Generated(hash = 77021336)
    public ChemistCart(Long id, String DOC_ID, String Stockist_Client_id, String Items,String Itemname, String Amount, String Remarks, Boolean Salesman, Boolean order_sync, String Product_ID, String Qty, String UOM, String Rate, String Price, String MRP,String PACK , String Createdon, String scheme,String sub_stkID,String minQ,String maxQ) {
        this.id = id;
        this.DOC_ID = DOC_ID;
        this.Stockist_Client_id = Stockist_Client_id;
        this.Items = Items;
        this.Itemname = Itemname;
        this.Amount = Amount;
        this.Remarks = Remarks;
        this.Salesman = Salesman;
        this.order_sync = order_sync;
        this.Product_ID = Product_ID;
        this.Qty = Qty;
        this.UOM = UOM;
        this.Rate = Rate;
        this.Price = Price;
        this.MRP = MRP;
        this.PACK = PACK ;
        this.Createdon = Createdon;
        this.Scheme = scheme;
        this.Sub_stkID = sub_stkID;
        this.minQ = minQ;
        this.maxQ = maxQ;
    }

    public String getMinQ() {
        return minQ;
    }

    public void setMinQ(String minQ) {
        this.minQ = minQ;
    }

    public String getMaxQ() {
        return maxQ;
    }

    public void setMaxQ(String maxQ) {
        this.maxQ = maxQ;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDOC_ID() {
        return DOC_ID;
    }

    public void setDOC_ID(String DOC_ID) {
        this.DOC_ID = DOC_ID;
    }

    public String getStockist_Client_id() {
        return Stockist_Client_id;
    }

    public void setStockist_Client_id(String Stockist_Client_id) {
        this.Stockist_Client_id = Stockist_Client_id;
    }

    @Bindable
    public String getItems() {
        return Items;
    }

    public void setItems(String Items) {
        this.Items = Items;
    }

    @Bindable
    public String getItemname() {
        return Itemname;
    }

    public void setItemname(String itemname) {
        Itemname = itemname;
    }


    public String getAmount() {
        return Amount;
    }

    public void setAmount(String Amount) {
        this.Amount = Amount;
    }

    public String getRemarks() {
        return Remarks;
    }

    public void setRemarks(String Remarks) {
        this.Remarks = Remarks;
    }

    public Boolean getSalesman() {
        return Salesman;
    }

    public void setSalesman(Boolean salesman) {
        Salesman = salesman;
    }

    public Boolean getOrder_sync() {
        return order_sync;
    }

    public void setOrder_sync(Boolean order_sync) {
        this.order_sync = order_sync;
    }

    public String getProduct_ID() {
        return Product_ID;
    }

    public void setProduct_ID(String Product_ID) {
        this.Product_ID = Product_ID;
    }

    @Bindable
    public String getQty() {
        return Qty;
    }

    public void setQty(String Qty) {
        this.Qty = Qty;
    }

    public String getUOM() {
        return UOM;
    }

    public void setUOM(String UOM) {
        this.UOM = UOM;
    }

    public String getRate() {
        return Rate;
    }

    public void setRate(String Rate) {
        this.Rate = Rate;
    }

    public String getPrice() {
        return Price;
    }

    public void setPrice(String Price) {
        this.Price = Price;
    }

    @Bindable
    public String getMRP() {
        return MRP;
    }

    public void setMRP(String MRP) {
        this.MRP = MRP;
    }

    public String getCreatedon() {
        return Createdon;
    }

    public String getPACK() {
        return PACK;
    }

    public void setPACK(String PACK) {
        this.PACK = PACK;
    }

    public void setCreatedon(String Createdon) {
        this.Createdon = Createdon;
    }

    public String getScheme() {
        return Scheme;
    }

    public void setScheme(String scheme) {
        Scheme = scheme;
    }
    public String getPercentScheme() {
        return PercentScheme;
    }

    public void setPercentScheme(String percentScheme) {
        PercentScheme = percentScheme;
    }

    public String getHalfScheme() {
        return HalfScheme;
    }

    public void setHalfScheme(String halfScheme) {
        HalfScheme = halfScheme;
    }

    public String getSub_stkID() {
        return Sub_stkID;
    }

    public void setSub_stkID(String sub_stkID) {
        Sub_stkID = sub_stkID;
    }
}
