package com.synergy.keimed_ordergenie.database;

import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.util.Log;

import org.greenrobot.greendao.AbstractDaoMaster;
import org.greenrobot.greendao.database.StandardDatabase;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseOpenHelper;
import org.greenrobot.greendao.identityscope.IdentityScopeType;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * Master of DAO (schema version 1000): knows all DAOs.
 */
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 5000;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(Database db, boolean ifNotExists) {
        StockistProductsDao.createTable(db, ifNotExists);
        ChemistCartDao.createTable(db, ifNotExists);
        ChemistOrderSyncDao.createTable(db, ifNotExists);
        LegendMasterDao.createTable(db, ifNotExists);
        ChemistOrderDao.createTable(db, ifNotExists);
        MasterPlacedOrderDao.createTable(db, ifNotExists);
    }

    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(Database db, boolean ifExists) {
        StockistProductsDao.dropTable(db, ifExists);
        ChemistCartDao.dropTable(db, ifExists);
        ChemistOrderSyncDao.dropTable(db, ifExists);
        LegendMasterDao.dropTable(db, ifExists);
        ChemistOrderDao.dropTable(db, ifExists);
        MasterPlacedOrderDao.dropTable(db, ifExists);
    }

    /**
     * WARNING: Drops all table on Upgrade! Use only during development.
     * Convenience method using a {@link DevOpenHelper}.
     */
    public static DaoSession newDevSession(Context context, String name) {
        Database db = new DevOpenHelper(context, name).getWritableDb();
        DaoMaster daoMaster = new DaoMaster(db);
        return daoMaster.newSession();
    }

    public DaoMaster(SQLiteDatabase db) {
        this(new StandardDatabase(db));
    }

    public DaoMaster(Database db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(StockistProductsDao.class);
        registerDaoClass(ChemistCartDao.class);
        registerDaoClass(ChemistOrderSyncDao.class);
        registerDaoClass(LegendMasterDao.class);
        registerDaoClass(ChemistOrderDao.class);
        registerDaoClass(MasterPlacedOrderDao.class);
    }

    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }

    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }

    /**
     * Calls {@link #createAllTables(Database, boolean)} in {@link #onCreate(Database)} -
     */
    public static abstract class OpenHelper extends DatabaseOpenHelper {
        public OpenHelper(Context context, String name) {
            super(context, name, SCHEMA_VERSION);
        }

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(Database db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }

    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name) {
            super(context, name);
        }

        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(Database db, int oldVersion, int newVersion) {
        Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            /*dropAllTables(db, true);
            onCreate(db);*/
//       Waseem new Update
            if(!isColumnExists(db,"CHEMIST_CART","MINQ")){
                db.execSQL("ALTER TABLE CHEMIST_CART ADD COLUMN MINQ TEXT;");
                db.execSQL("ALTER TABLE CHEMIST_CART ADD COLUMN MAXQ TEXT;");
            }

        }
    }
    public static boolean isColumnExists (Database db,String table, String column) {

        Cursor cursor = db.rawQuery("PRAGMA table_info("+ table +")", null);

        if (cursor != null) {

            while (cursor.moveToNext()) {

                String name = cursor.getString(cursor.getColumnIndexOrThrow("name"));

                if (column.equalsIgnoreCase(name)) {

                    return true;

                }

            }

        }



        return false;

    }

}
