package com.synergy.keimed_ordergenie.database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "LEGEND_MASTER".
 */
@Entity
public class LegendMaster {

    @Id(autoincrement = true)
    private Long id;
    private String stockistId;
    private String LegendName;
    private String ColorCode;
    private String StartRange;
    private String EndRange;
    private String StockLegendID;
    private String LegendMode;

    @Generated(hash = 609706601)
    public LegendMaster() {
    }

    public LegendMaster(Long id) {
        this.id = id;
    }

    @Generated(hash = 368125238)
    public LegendMaster(Long id, String stockistId, String LegendName, String ColorCode, String StartRange, String EndRange, String StockLegendID, String LegendMode) {
        this.id = id;
        this.stockistId = stockistId;
        this.LegendName = LegendName;
        this.ColorCode = ColorCode;
        this.StartRange = StartRange;
        this.EndRange = EndRange;
        this.StockLegendID = StockLegendID;
        this.LegendMode = LegendMode;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getStockistId() {
        return stockistId;
    }

    public void setStockistId(String stockistId) {
        this.stockistId = stockistId;
    }

    public String getLegendName() {
        return LegendName;
    }

    public void setLegendName(String LegendName) {
        this.LegendName = LegendName;
    }

    public String getColorCode() {
        return ColorCode;
    }

    public void setColorCode(String ColorCode) {
        this.ColorCode = ColorCode;
    }

    public String getStartRange() {
        return StartRange;
    }

    public void setStartRange(String StartRange) {
        this.StartRange = StartRange;
    }

    public String getEndRange() {
        return EndRange;
    }

    public void setEndRange(String EndRange) {
        this.EndRange = EndRange;
    }

    public String getStockLegendID() {
        return StockLegendID;
    }

    public void setStockLegendID(String StockLegendID) {
        this.StockLegendID = StockLegendID;
    }

    public String getLegendMode() {
        return LegendMode;
    }

    public void setLegendMode(String LegendMode) {
        this.LegendMode = LegendMode;
    }

}
