package com.synergy.keimed_ordergenie.database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "MASTER_PLACED_ORDER".
 */
@Entity
public class MasterPlacedOrder {

    @Id(autoincrement = true)
    private Long id;
    private String json;
    private String customerID;
    private String doc_ID;

    public MasterPlacedOrder() {
    }

    public MasterPlacedOrder(Long id) {
        this.id = id;
    }

    public MasterPlacedOrder(Long id, String json, String customerID, String doc_ID) {
        this.id = id;
        this.json = json;
        this.customerID = customerID;
        this.doc_ID = doc_ID;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getJson() {
        return json;
    }

    public void setJson(String json) {
        this.json = json;
    }

    public String getCustomerID() {
        return customerID;
    }

    public void setCustomerID(String customerID) {
        this.customerID = customerID;
    }

    public String getDoc_ID() {
        return doc_ID;
    }

    public void setDoc_ID(String doc_ID) {
        this.doc_ID = doc_ID;
    }


}
