package com.synergy.keimed_ordergenie.database;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "STOCKIST_PRODUCTS".
 */
@Entity(
        indexes = {
                @Index(value = "Product_ID", unique = true)
        }
)

@JsonIgnoreProperties(ignoreUnknown = true)
public class StockistProducts {
    @Id(autoincrement = true)
    private Long id;
    private String Itemcode;
    private String Stockist_id;
    private String Product_ID;
    private String Itemname;
    private String Packsize;
    private String MRP;
    private String Rate;
    private String Stock;
    private String type;
    private String MfgCode;
    private String MfgName;
    private String DoseForm;
    private String Scheme;
    private String PercentScheme;
    private String HalfScheme;
    private String LegendName;
    private String LegendColor;
    private String BoxSize;
    private String replaceName;


    private String MinQ;
    private String MaxQ;



    public String getReplaceName() {
        return replaceName;
    }

    public void setReplaceName(String replaceName) {
        this.replaceName = replaceName;
    }
    /*  PercentScheme
HalfScheme */

    @Generated(hash = 1018877611)
    public StockistProducts() {
    }

    public StockistProducts(Long id) {
        this.id = id;
    }



    @Generated(hash = 1225321988)
    public StockistProducts(Long id, String Itemcode, String Stockist_id, String Product_ID, String Itemname, String Packsize, String MRP, String Rate, String Stock, String type, String MfgCode, String MfgName, String DoseForm, String Scheme, String HalfScheme,String PercentScheme,String LegendName,String LegendColor ,String BoxSize,String minQ,String maxQ ) {
        this.id = id;
        this.Itemcode = Itemcode;
        this.Stockist_id = Stockist_id;
        this.Product_ID = Product_ID;
        this.Itemname = Itemname;
        this.Packsize = Packsize;
        this.MRP = MRP;
        this.Rate = Rate;
        this.Stock = Stock;
        this.type = type;
        this.MfgCode = MfgCode;
        this.MfgName = MfgName;
        this.DoseForm = DoseForm;
        this.Scheme = Scheme;
        this.HalfScheme = HalfScheme;
        this.PercentScheme = PercentScheme;
        this.LegendName = LegendName;
        this.LegendColor = LegendColor;
        this.BoxSize = BoxSize;
        this.MinQ=minQ;
        this.MaxQ=maxQ;

        this.replaceName = Itemname.replace("-", "").replace(" ", "").replace("(", "").replace(")", "")
                .replace("/", "").replace("*", "")
                .replace(":", "").replace("_", "").replace(".", "").replace("'", "").replace("`", "").replace("~", "").
                        replace("^", "").replace("+", "")
                .replace(",", "").replace("<","").
                        replace(">","").toLowerCase();
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getItemcode() {
        return Itemcode;
    }

    public void setItemcode(String Itemcode) {
        this.Itemcode = Itemcode;
    }

    public String getStockist_id() {
        return Stockist_id;
    }

    public void setStockist_id(String Stockist_id) {
        this.Stockist_id = Stockist_id;
    }

    public String getProduct_ID() {
        return Product_ID;
    }

    public void setProduct_ID(String Product_ID) {
        this.Product_ID = Product_ID;
    }

    public String getItemname() {
        return Itemname;
    }

    public void setItemname(String Itemname) {
        this.Itemname = Itemname;
    }

    public String getPacksize() {
        return Packsize;
    }

    public void setPacksize(String Packsize) {
        this.Packsize = Packsize;
    }

    public String getMRP() {
        return MRP;
    }

    public void setMRP(String MRP) {
        this.MRP = MRP;
    }

    public String getRate() {
        return Rate;
    }

    public void setRate(String Rate) {
        this.Rate = Rate;
    }

    public String getStock() {
        return Stock;
    }

    public void setStock(String Stock) {
        this.Stock = Stock;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getMfgCode() {
        return MfgCode;
    }

    public void setMfgCode(String MfgCode) {
        this.MfgCode = MfgCode;
    }

    public String getMfgName() {
        return MfgName;
    }

    public void setMfgName(String MfgName) {
        this.MfgName = MfgName;
    }

    public String getDoseForm() {
        return DoseForm;
    }

    public void setDoseForm(String DoseForm) {
        this.DoseForm = DoseForm;
    }

    public String getScheme() {
        return Scheme;
    }

    public void setScheme(String Scheme) {
        this.Scheme = Scheme;
    }

    public String getHalfScheme() {
        return HalfScheme;
    }

    public void setHalfScheme(String HalfScheme) {
        this.HalfScheme = HalfScheme;
    }

    public String getPercentScheme() {
        return PercentScheme;
    }

    public void setPercentScheme(String PercentScheme) {
        this.PercentScheme = PercentScheme;
    }
    public String getLegendName() {
        return LegendName;
    }

    public void setLegendName(String legendName) {
        LegendName = legendName;
    }

    public String getLegendColor() {
        return LegendColor;
    }

    public void setLegendColor(String legendColor) {
        LegendColor = legendColor;
    }

    public String getBoxSize() {
        return BoxSize;
    }

    public void setBoxSize(String boxSize) {
        BoxSize = boxSize;
    }

    public String getMinQ() {
        return MinQ;
    }

    public void setMinQ(String minQ) {
        MinQ = minQ;
    }

    public String getMaxQ() {
        return MaxQ;
    }

    public void setMaxQ(String maxQ) {
        MaxQ = maxQ;
    }
}
